### ISSUE TITLE
Command not working, most likely to incompatibility with other mods editing terminal

### ISSUE THREAD

**Issue by Fl4sHNoX** [AidanTweedy/scanplus#1]
Description:

Able to purchase the `Infrared Scanner` ship upgrade, used the following commands but none seemed to work:

- `scan`
- `infrared scan`
- `ir scan`
- `life scan`
- `scan life`

The issue may be related to having one or more of the following mods installed with ScanPlus:

- [LethalTerminalFormatter](https://github.com/AndreyMrovol/LethalTerminalFormatter)
- [LC-TerminalConflictFix](https://github.com/SylviBlossom/LC-TerminalConflictFix)

**Comment by AidanTweedy** [comment]
Thanks for reporting this - I believe I narrowed it down to a compatibility issue with `LethalTerminalFormatter` and should have a patch out soon!

**Comment by AidanTweedy** [comment]
Working!

![Screenshot 2024-03-22 214254](https://github.com/AidanTweedy/scanplus/assets/31974288/50b45d3c-15d0-4211-9edc-fb88a07f723a)
